---
title: Aevum
description: Buy Jewelry, Diamonds, Gems, Gold & Silver online or offline  — We do
  wholesale too!
company-name:
  en: AEVUM Premium Trading S.A.
  el: AEVUM Premium Trading Α.Ε.
email: contact@aevum-sa.com
phone: "+30 210 322 7148"
address:
  en: Lekka 23-25,<br>105 62 Athens, Greece
  el: Λέκκα 23-25,<br>105 62 Αθήνα
opening-hours:
  en: "<strong>Mon – Fri</strong>: 09:00 – 17:00<br><strong>Saturday</strong>: 10:00
    – 14:00"
  el: "<strong>Δευ — Παρ</strong>: 09:00 – 17:00<br><strong>Σάββατο</strong>: 10:00
    – 14:00"
hero-image: /images/hero-image.jpg
markdown: kramdown
permalink: pretty
exclude:
- Gemfile
- Gemfile.lock
- README.md
- ".DS_Store"
