---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: document
  path: _config.yml
  label: Company Info
- type: document
  path: _data/faq.yml
  label: FAQ
- type: heading
  label: Components
- type: document
  path: _data/navbar.yml
  label: Navigation Menu
- type: document
  path: _data/footer.yml
  label: Footer
- type: document
  path: _data/cta.yml
  label: CTA
- type: document
  path: _data/categories.yml
  label: Categories
- type: heading
  label: Pages
- type: document
  path: _data/home.yml
  label: Home
- type: document
  path: _data/grading.yml
  label: Grading
- type: document
  path: _data/contact.yml
  label: Contact
- type: document
  path: _data/404.yml
  label: 404 Error
- type: jekyll-posts
  label: Posts
  create: all
- type: directory
  path: _data/text-pages
  label: All Text Pages
  create: all
  match: "*.md"
  new_doc_ext: md
- type: heading
  label: Wholesale Pages
- type: document
  path: _data/wholesale-gems.yml
  label: Gemstones
- type: document
  path: _data/wholesale-jewelry.yml
  label: Jewelry
- type: document
  path: _data/wholesale-metals.yml
  label: Metals
- type: heading
  label: Other
- type: directory
  path: _data
  label: All Text Content
  create: all
  match: "*.yml"
  new_doc_ext: yml
- type: jekyll-pages
  label: Pages
  create: all
  templates:
  - page-with-text
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - JEKYLL_ENV=staging
  preview_output_directory: _site
  install_dependencies_command: bundle install --path vendor/bundle
  preview_docker_image: forestryio/ruby:2.6
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: bundle exec jekyll serve --drafts --unpublished --future
    -d _site
