---
label: X-DO NOT USE - Configuration
hide_body: true
fields:
- type: text
  name: title
  label: Website Main Title
  description: 'This will be shown in Google Search result and as the description
    in the visitor’s browser window. It will be shown before the page name, as such:
    “Website title | Page Title”'
- type: text
  name: description
  label: Website Description
  description: This will be shown in Google Search results under the website/page
    title.
- type: field_group
  name: company-name
  label: Company Name
  fields:
  - type: text
    name: en
    label: English
  - type: text
    name: el
    label: Greek
- type: text
  name: email
  label: Email
- type: text
  name: phone
  label: Phone
- type: field_group
  name: address
  label: Address
  fields:
  - type: textarea
    name: en
    label: English
    config:
      wysiwyg: true
      schema:
        format: html
  - type: textarea
    name: el
    label: Greek
    config:
      wysiwyg: true
      schema:
        format: html
- type: field_group
  name: opening-hours
  label: Opening Hours
  fields:
  - type: textarea
    name: en
    label: English
    config:
      wysiwyg: true
      schema:
        format: html
  - type: textarea
    name: el
    label: Greek
    config:
      wysiwyg: true
      schema:
        format: html
- type: text
  name: markdown
  label: markdown
  hidden: true
- type: text
  name: permalink
  label: permalink
  hidden: true
- type: list
  name: exclude
  label: exclude
  hidden: true
pages:
- _config.yml
